### PR TITLE
OCPBUGS-38317: scheduler-plugins change causes CrashLoopBackOff

### PR DESCRIPTION
**Pull request by prb112**
Fixes an issue with /bin/kube-scheduler path and scheduler-plugins image

### CODE REVIEW

**Comment by ingvagabund** [comment]
This is a breaking change as the suggested fix does not work for `registry.k8s.io/scheduler-plugins/kube-scheduler:v0.28.9`:
```
time="2024-08-13T10:23:45Z" level=error msg="runc create failed: unable to start container process: exec: \"--config=/etc/kubernetes/config.yaml\": stat --config=/etc/kubernetes/config.yaml: no such file or directory"
  Normal   Pulled  9s (x3 over 10s)  kubelet  Container image "registry.k8s.io/scheduler-plugins/kube-scheduler:v0.28.9" already present on machine
  Warning  Failed  9s                kubelet  Error: container create failed: time="2024-08-13T10:23:46Z" level=error msg="runc create failed: unable to start container process: exec: \"--config=/etc/kubernetes/config.yaml\": stat --config=/etc/kubernetes/config.yaml: no such file or directory"
```

**Comment by ingvagabund** [comment]
The binary path changed as well. From /bin/kube-scheduler to /kube-scheduler. The images before `registry.k8s.io/scheduler-plugins/kube-scheduler:v0.29.7` have the binary at `/bin/kube-scheduler`.

**Comment by ingvagabund** [comment]
Asking Wei for the motivation to change the location in https://kubernetes.slack.com/archives/C09TP78DV/p1723546975114219.

**Comment by ingvagabund** [comment]
Our documentation currently mentions "The custom scheduler must have the /bin/kube-scheduler binary and be based on the Kubernetes scheduling framework.". I'd like to avoid introducing a new param for setting up the command. This is quite unpleasant change.

[1] https://docs.openshift.com/container-platform/4.16/nodes/scheduling/secondary_scheduler/index.html

**Comment by prb112** [comment]
Yes, I agree. I had tested it with the original location.

**Comment by prb112** [comment]
Hey @ingvagabund I had to use a cmd override to get it to work. Are you seeing the same thing? Thanks, Paul

**Comment by ingvagabund** [comment]
Yeah, `command` is the way to do it from now on.

**Comment by ingvagabund** [comment]
@prb112 thank you

**Pull request merged**
