### PR TITLE
WRKLDS-700: bump(k8s) to v0.27.1

### PR DESCRIPTION
**Pull request by knelasevero**
title says it all

### CODE REVIEW

**Comment by ingvagabund** [comment]
https://github.com/openshift/secondary-scheduler-operator/blob/master/.ci-operator.yaml needs to be bumped as well. rhel-8-release-golang-1.19-openshift-4.13 -> rhel-8-release-golang-1.20-openshift-4.14

**Comment by ingvagabund** [comment]
@knelasevero would you please also bump `github.com/openshift/*` dependencies?

**Comment by knelasevero** [comment]
> @knelasevero would you please also bump `github.com/openshift/*` dependencies?

Done :heavy_check_mark:

**Pull request closed without merging**
